version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "algafood"
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql