management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
